### ISSUE TITLE
#3 Motor Offsets

### ISSUE THREAD

**Issue by BrendanAnnable** [NUbots/robocup#35]
Robot 3 will now run the binary fine, however there it something wrong with at least 1 motor in his left leg.

The torque is on, but the leg is at a completely wrong angle (probably ~30-40 degrees out), suggesting that the motor offsets are wrong?

The rest of him seems to function perfectly fine.

**Comment by mmetcalfe** [comment]
I'm not really sure how to set motor offsets.
I'll try to have a look tonight, though.

**Comment by WongAaronSW** [comment]
Try the Dynamixel motor viewer (Roboplus Manager). You'll need to use that USB to TTL converter to talk to the motor directly.
Otherwise you can fudge the angles in the interface file (Joint Mappings) in the NUPlatform/Platforms/Darwin to test your theory.

Regards,
Aaron Wong

Date: Wed, 29 May 2013 00:54:25 -0700

**Comment by BrendanAnnable** [comment]
This is now fixed I believe?
